spring:
  redis:
    port: 6379
    host: 10.1.33.126
    password: 123456
    database: 0

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: true
    #数据库访问配置
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://10.1.32.69:3306/arrail-resource-server?useUnicode=true&characterEncoding=utf-8
    #username: root
    #password: 1qaz@WSX
    url: jdbc:mysql://10.1.33.81:3306/mysell?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&
    username: root
    password: 123456
    validationQuery: SELECT 1 FROM DUAL

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml

